enum {
	BUTTON_UNDO,
	BUTTON_HINT,
	BUTTON_SAVE_STATE,
	BUTTON_LOAD_STATE,
	BUTTON_NEW,
	BUTTON_RESTART,
	BUTTON_SELECT_LEVEL,
	BUTTON_PREV_LEVEL,
	BUTTON_NEXT_LEVEL,
	NUM_BUTTONS
};

int get_button_at(int x, int y);
